CareConnect/CareConnect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("receiptionist.urls")),
    path('doctor/', include("doctor.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
]+ static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

CareConnect/doctor/urls.py
from django.urls import path, include,re_path  
from . import views
from django.contrib.auth import views as auth_views

app_name="doctor"

urlpatterns = [
    path("home/", views.home, name="home"),
    path('login/', views.doctor_login, name='doctorlogin'),
]

CareConnect/receiptionist/urls.py
from django.urls import path, include,re_path  
from . import views
from django.contrib.auth import views as auth_views

app_name="receptionist"

urlpatterns = [
    path("", views.home, name="index"),
    path("receptionist/home/", views.home, name="home"),

    path('receptionist/login/', views.receptionist_login, name='receptionistLogin'),

    path("patientinformation/", views.patientinformation, name="patientinformation"),
    path("patientlist/", views.patientlist, name="patientlist"),

    path("doctorinformation/", views.doctorinformation, name="doctorinformation"),
    path("doctorlist/", views.doctorlist, name="doctorlist"),

    path("doctorlist/delete/<int:pk>", views.doctor_delete, name="doctor_delete"),
    path("patientlist/delete/<int:pk>", views.patient_delete, name="patient_delete"),
    path("hospitallist/delete/<int:pk>", views.hospital_delete, name="hospital_delete"),


    path('patientlist/update/<int:pk>', views.PatientUpdate.as_view(), name='patientlist_update'),
    path('doctorlist/update/<int:pk>', views.DoctorUpdate.as_view(), name='doctorlist_update'),
    path('hospitallist/update/<int:pk>', views.HospitalUpdate.as_view(), name='hospitallist_update'),


    path("hospitalinformation/", views.hospitalinformation, name="hospitalinformation"),
    path("hospitallist/", views.hospitallist, name="hospitallist"),

    path('appointment/', views.appointment_list, name='appointment_list'),
    
    path('update/<int:pk>/', views.appointment_update, name='appointment_update'),
    path('delete/<int:pk>/', views.appointment_delete, name='appointment_delete'),

    path('doctor_login/', auth_views.LoginView.as_view(template_name='registration/doctor_login.html'), name='doctor_login'),

    path('doctor_appointment_view/', views.doctor_appointment_view, name='doctor_appointment_view'),

     path("logout/", views.logout_view, name="logout"),
]

CareConnect/doctor/models.py
from django.db import models

# Create your models here.

CareConnect/doctor/views.py
from django.shortcuts import render, redirect
from receiptionist.models import Appointment,Doctor
from django.http import JsonResponse, HttpResponse
# from .forms import *
from django.views.generic import View
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm


# Create your views here.
def home(request):
    doctor = Doctor.objects.filter(user=request.user).first()
    appointments = Appointment.objects.filter(doctor = doctor)
    return render(request, "doctor/doctor_appointment_view.html", {"appointments": appointments})

def doctor_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            if user is not None and user.groups.filter(name='doctor').exists():
                login(request, user)
                return redirect("doctor:home") 
            else:
                return HttpResponse("You don't have permission to access this page. Please contact staff or admin.")
    else:
        form = AuthenticationForm()
    
    return render(request, 'registration/doctor_login.html', {'form': form})

CareConnect/templates/doctor/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title> DjandoEHR </title>
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <style>
       
              /* Google Fonts Import Link */
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');
        *{
          margin: 0;
          padding: 0;
          box-sizing: border-box;
          font-family: 'Poppins', sans-serif;
        }
        .sidebar{
          position: fixed;
          top: 0;
          left: 0;
          height: 100%;
          width: 260px;
          background: #11101d;
          z-index: 100;
          transition: all 0.5s ease;
        }
        .sidebar.close{
          width: 78px;
        }
        .sidebar .logo-details{
          height: 60px;
          width: 100%;
          display: flex;
          align-items: center;
        }
        .sidebar .logo-details i{
          font-size: 30px;
          color: #fff;
          height: 50px;
          min-width: 78px;
          text-align: center;
          line-height: 50px;
        }
        .sidebar .logo-details .logo_name{
          font-size: 22px;
          color: #fff;
          font-weight: 600;
          transition: 0.3s ease;
          transition-delay: 0.1s;
        }
        .sidebar.close .logo-details .logo_name{
          transition-delay: 0s;
          opacity: 0;
          pointer-events: none;
        }
        .sidebar .nav-links{
          height: 100%;
          padding: 30px 0 150px 0;
          overflow: auto;
        }
        .sidebar.close .nav-links{
          overflow: visible;
        }
        .sidebar .nav-links::-webkit-scrollbar{
          display: none;
        }
        .sidebar .nav-links li{
          position: relative;
          list-style: none;
          transition: all 0.4s ease;
        }
        .sidebar .nav-links li:hover{
          background: #1d1b31;
        }
        .sidebar .nav-links li .iocn-link{
          display: flex;
          align-items: center;
          justify-content: space-between;
        }
        .sidebar.close .nav-links li .iocn-link{
          display: block
        }
        .sidebar .nav-links li i{
          height: 50px;
          min-width: 78px;
          text-align: center;
          line-height: 50px;
          color: #fff;
          font-size: 20px;
          cursor: pointer;
          transition: all 0.3s ease;
        }
        .sidebar .nav-links li.showMenu i.arrow{
          transform: rotate(-180deg);
        }
        .sidebar.close .nav-links i.arrow{
          display: none;
        }
        .sidebar .nav-links li a{
          display: flex;
          align-items: center;
          text-decoration: none;
        }
        .sidebar .nav-links li a .link_name{
          font-size: 18px;
          font-weight: 400;
          color: #fff;
          transition: all 0.4s ease;
        }
        .sidebar.close .nav-links li a .link_name{
          opacity: 0;
          pointer-events: none;
        }
        .sidebar .nav-links li .sub-menu{
          padding: 6px 6px 14px 80px;
          margin-top: -10px;
          background: #1d1b31;
          display: none;
        }
        .sidebar .nav-links li.showMenu .sub-menu{
          display: block;
        }
        .sidebar .nav-links li .sub-menu a{
          color: #fff;
          font-size: 15px;
          padding: 5px 0;
          white-space: nowrap;
          opacity: 0.6;
          transition: all 0.3s ease;
        }
        .sidebar .nav-links li .sub-menu a:hover{
          opacity: 1;
        }
        .sidebar.close .nav-links li .sub-menu{
          position: absolute;
          left: 100%;
          top: -10px;
          margin-top: 0;
          padding: 10px 20px;
          border-radius: 0 6px 6px 0;
          opacity: 0;
          display: block;
          pointer-events: none;
          transition: 0s;
        }
        .sidebar.close .nav-links li:hover .sub-menu{
          top: 0;
          opacity: 1;
          pointer-events: auto;
          transition: all 0.4s ease;
        }
        .sidebar .nav-links li .sub-menu .link_name{
          display: none;
        }
        .sidebar.close .nav-links li .sub-menu .link_name{
          font-size: 18px;
          opacity: 1;
          display: block;
        }
        .sidebar .nav-links li .sub-menu.blank{
          opacity: 1;
          pointer-events: auto;
          padding: 3px 20px 6px 16px;
          opacity: 0;
          pointer-events: none;
        }
        .sidebar .nav-links li:hover .sub-menu.blank{
          top: 50%;
          transform: translateY(-50%);
        }
        .sidebar .profile-details{
          position: fixed;
          bottom: 0;
          width: 260px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          background: #1d1b31;
          padding: 12px 0;
          transition: all 0.5s ease;
        }
        .sidebar.close .profile-details{
          background: none;
        }
        .sidebar.close .profile-details{
          width: 78px;
        }
        .sidebar .profile-details .profile-content{
          display: flex;
          align-items: center;
        }
        .sidebar .profile-details img{
          height: 52px;
          width: 52px;
          object-fit: cover;
          border-radius: 16px;
          margin: 0 14px 0 12px;
          background: #1d1b31;
          transition: all 0.5s ease;
        }
        .sidebar.close .profile-details img{
          padding: 10px;
        }
        .sidebar .profile-details .profile_name,
        .sidebar .profile-details .job{
          color: #fff;
          font-size: 18px;
          font-weight: 500;
          white-space: nowrap;
        }
        .sidebar.close .profile-details i,
        .sidebar.close .profile-details .profile_name,
        .sidebar.close .profile-details .job{
          display: none;
        }
        .sidebar .profile-details .job{
          font-size: 12px;
        }
        .home-section{
          position: relative;
          background: #E4E9F7;
          height: 100vh;
          left: 260px;
          width: calc(100% - 260px);
          transition: all 0.5s ease;
        }
        .sidebar.close ~ .home-section{
          left: 78px;
          width: calc(100% - 78px);
        }
        .home-section .home-content{
          height: 60px;
          display: flex;
          align-items: center;
        }
        .home-section .home-content .bx-menu,
        .home-section .home-content .text{
          color: #11101d;
          font-size: 35px;
        }
        .home-section .home-content .bx-menu{
          margin: 0 15px;
          cursor: pointer;
        }
        .home-section .home-content .text{
          font-size: 26px;
          font-weight: 600;
        }
        @media (max-width: 400px) {
          .sidebar.close .nav-links li .sub-menu{
            display: none;
          }
          .sidebar{
            width: 78px;
          }
          .sidebar.close{
            width: 0;
          }
          .home-section{
            left: 78px;
            width: calc(100% - 78px);
            z-index: 100;
          }
          .sidebar.close ~ .home-section{
            width: 100%;
            left: 0;
          }

        }
     </style>
     {%block extracss%}
     {%endblock extracss%}

   </head>
<body>
  <div class="sidebar close">
    
    <ul class="nav-links">
      {% if request.user.is_authenticated %}
      <li>
        <a href="{% url 'doctor:home' %}">
          <i class='bx bx-grid-alt' ></i>
          <span class="link_name">Dashboard</span>
        </a>
        
      </li>
      
      <li>
        <div class="iocn-link">
          <a href="{% url 'doctor:home' %}">
            <i class='bx bx-plug' ></i>
            <span class="link_name">Appointments</span>
          </a>
        
        </div>
      
      </li>
      {%endif%}
    
      <li>
        <div class="iocn-link">
          <a href="#">
            <i class='bx bx-plug' ></i>
            <span class="link_name">Account</span>
          </a>
          <i class='bx bxs-chevron-down arrow' ></i>
        </div>
        <ul class="sub-menu">
          
          {% if request.user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>  
          {%else%}

          <li><a href="{% url 'receptionist:receptionistLogin' %}">Receiptionist Login</a></li>
          <li><a href="{% url 'doctor:doctorlogin' %}">Doctor Login</a></li>

          <li><a href="/admin">Admin Login</a></li>
  
          {%endif%}
          
        </ul>
      </li>
  </li>
</ul>
  </div>
  <section class="home-section">
    <div class="home-content">
      <i class='bx bx-menu' ></i>
      <span class="text">Django Care-Connect</span>
    </div>
    <div class="main-content" >
      {%block content%}
      {%endblock%}

    </div>
  </section>
  <script>
      let arrow = document.querySelectorAll(".arrow");
      for (var i = 0; i < arrow.length; i++) {
        arrow[i].addEventListener("click", (e)=>{
      let arrowParent = e.target.parentElement.parentElement;
      arrowParent.classList.toggle("showMenu");
        });
      }
      let sidebar = document.querySelector(".sidebar");
      let sidebarBtn = document.querySelector(".bx-menu");
      console.log(sidebarBtn);
      sidebarBtn.addEventListener("click", ()=>{
        sidebar.classList.toggle("close");
      });
  </script>
  {%block extrajs%}
  {%endblock extrajs%}
</body>
</html>

CareConnect/templates/doctor/doctor_appointment_view.html
{% extends "doctor/base.html" %}
{% block content %}
{% block extrascripts %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-oC2pKwMEw5/4Pp3FNYu5b8NA5SxmFpo5Ko5r5+5f5v5Bk5x5Ko5r5+5f5v5Bk5x5Ko" crossorigin="anonymous">

<!-- DataTables JavaScript -->
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function() {
        $('#example').DataTable(); 
    });
</script>
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap-extended.min.css">
<link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/fonts/simple-line-icons/style.min.css">
<link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/colors.min.css">
<link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
{% endblock extrascripts %}

<br>
<div class="grey-bg container-fluid">
      <div class="col-12">
        <div class="card">
          <div class="card-content">
            <div class="card-body">
              <table id="example" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr style="text-align:center">
                      <th>Title</th>
                      <th>Details</th>
                      <th>Doctor</th>
                      <th>Patient Name</th>
                      <th>Start Time</th>
                      <th>End Time</th>
                    </tr>
                </thead>
                <tbody>
                    {% for x in appointments %}
                    <tr>
                        <td>{{ x.title }}</td>
                        <td>{{ x.detail }}</td>
                        <td>{{ x.doctor }}</td>

                        <td>{{ x.patient }}</td>
                        <td>{{ x.start_datetime }}</td>
                        <td>{{ x.end_datetime }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>


{% endblock %}

CareConnect/templates/doctor/patient.html
{% extends "receiptionist/base.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% load static %}
<link href="{% static 'css/jquery.toast.css' %}" rel="stylesheet">

<script src="https://cdnjs.cloudflare.com/ajax/libs/javascript.util/0.12.12/javascript.util.min.js" integrity="sha512-oHBLR38hkpOtf4dW75gdfO7VhEKg2fsitvHZYHZjObc4BPKou2PGenyxA5ZJ8CCqWytBx5wpiSqwVEBy84b7tw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>  
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>

{% if error_msg%}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="{% static 'javascript/jquery.toast.js' %}"></script>
  <script>

      toastr.error('{{error_msg}}', '{{title}}');
  </script>
{% endif %}

<style>
  #parent {
    text-align: center;
  }
  form {
    display: inline-block;
    text-align: left;
    border: 1px solid ; 
    border-radius: 15px;
    padding: 20px; 
    background-color: lightgrey;
    height: auto;
  }
</style>
<br>
<br>
<br>
<br>
<br>
<br>
<div id="parent">
  <h2>Patient Information</h2>
  <br>
  <br>

  <form method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <br>
    <button type="submit" class="btn btn-primary" style="background-color: #5c3bdf; border-color: #5c3bdf">Submit</button>
  </form>
</div>
{% endblock %}

CareConnect/templates/doctor/patientlist.html
{% extends "receiptionist/base.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% load static %}
<link href="{% static 'css/jquery.toast.css' %}" rel="stylesheet">

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet"/>
<link href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap4.min.css" rel="stylesheet"/>
{% if error_msg%}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="{% static 'javascript/jquery.toast.js' %}"></script>
  <script>
    alert({{error_msg}})
      toastr.error('{{error_msg}}', '{{title}}');
  </script>
{% endif %}



<br><br><br><br><br>
<br><br>

<div class="container" style="text-align:center">
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr style="text-align:center">
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>MRN</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for x in information %}
            <tr>
                <td>{{ x.id }}</td>
                <td>{{ x.name }}</td>
                <td>{{ x.email }}</td>
                <td>{{ x.MRN }}</td>
                <td>
                    <a href="javascript:void(0)" class="btn btn-danger edit-button preview" ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                      </svg></a>
                </td>
                <td>
                    <a href="delete/{{ x.id }}" class="btn btn-danger" id="deleteBtn{{ x.id }}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                        <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                      </svg></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- Modal for updating patient information -->
<div class="modal fade" id="updatePatientModal" tabindex="-1" role="dialog" aria-labelledby="updatePatientModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updatePatientModalLabel">Update Patient Information</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="updatePatientForm">
                    {% csrf_token %}
    
                    <div class="form-group">
                        <label for="name">Name:</label>
                        <input type="text" id="name" name="name" value="">
                    </div>
                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input type="text" id="email" name="email" value="">
                    </div>
                
                
                    <input type="hidden" id="patientId" name="patientId" value="">
                    
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- Include jQuery library -->
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>

<!-- Include DataTables JavaScript library -->
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

<!-- Include DataTables Bootstrap JavaScript library -->
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap4.min.js"></script> 

<!-- Include Bootstrap JS -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        // Initialize DataTable
        var dataTable = $('#example').DataTable();

    

        // Handle form submission for updating patient information
        $('#updatePatientForm').on('submit', function (e) {
            e.preventDefault();
            var formData = $(this).serialize();
            var patientId = $('#patientId').val();
            $.ajax({
                type: 'POST',
                url: 'update/' + patientId,
                data: formData,
                success: function () {
                    location.reload();
                }
            });
        });
    });
    $(".preview").click(function () {

        var $modal = $("#updatePatientModal");
        let currentRow=$(this).parents('tr');
        var col1=currentRow.find("td:eq(1)").text();
        var col0=currentRow.find("td:eq(0)").text();

        var col2=currentRow.find("td:eq(2)").text();
        var col3=currentRow.find("td:eq(3)").text();
        
        
        document.getElementById('name').value = col1
        document.getElementById('patientId').value = col0
        document.getElementById('email').value = col2


        
        $modal.modal("show");

          
    });
</script>
{% endblock %}

CareConnect/templates/doctor/register.html
{% extends "receiptionist/base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<style>
  /* Center the form horizontally and vertically */
  html, body {
    height: 100%;
    margin: 0;
  }

  body {
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: #000; /* Set the background color to black */
  }

  form {  
    text-align: left;
    border: 2px solid white; /* Border around the form */
    padding: 20px; /* Padding inside the border */
    background-color: lightgrey; /* Background color inside the border */
    border-radius: 10px; /* Border radius */
    max-width: 400px; /* Maximum width of the form */
  }

  h2 {
    text-align: center; /* Center the heading */
  }
</style>

<h2>Patient information</h2>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <br>
  <br>
  <br>

  <button type="submit" style="background-color: #5c3bdf;">Log In</button>
</form>
{% endblock %}